sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.3
  - 5.6
  - 7.0

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

install:
  - phpenv config-rm xdebug.ini
  - composer update --prefer-source $PREFER_LOWEST


notifications:
  email:
    - alakhefifi@gmail.com
